console.log("Hello Winc Academy");
let name = "Frederika";
console.log(name);
let numberOne = 4;
let numberTwo = 4;
console.log(numberOne + numberTwo);
let stringOne = "4";
let stringTwo = "4";
console.log(stringOne + stringTwo);
let numberThree = 2;
let numberFour = 5;
console.log(numberOne + numberThree);
console.log(numberThree - numberTwo);
console.log(numberFour * numberThree);
console.log(numberOne / numberThree);
console.log(numberFour % numberThree);
let age = 48;
console.log(typeof age);
let age = "48";
console.log(typeof age);